### PR TITLE
Fix #3 redirect uri ignores HTTPS protocol

### LINKED ISSUE #3: redirect uri ignores HTTPS protocol
I'm trying to us this module on a secure domain (`https://www.my-domain.com`), but the redirect uri for the oauth request is set as `http://www.my-domain.com/auth/callback`. I think the problem is on this line:

https://github.com/samtgarson/nuxt-oauth/blob/0748fe36aef96b8df8c7f68a5d17f6473af632ff/lib/handler.js#L28

The oauth provider does not allow redirects starting with `http://`

### PR DESCRIPTION
**Pull request by Jexordexan**
use `x-forwarded-proto` instead of hardcoded `http`

### CODE REVIEW

**Comment by samtgarson** [comment]
Thanks for the PR!

I'm not sure `req.protocol` comes in a standard Node HTTP server? I just chucked up a quick test which prints out the request headers: https://headers.now.sh/, and it doesn't appear.

You could try [X-Forwarded-Proto](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-Proto) but should also probably default to `http` in case it's not there—[that also appears to be what express uses](https://github.com/expressjs/express/blob/b97faff6e2aa4d34d79485fe4331cb0eec13ad57/lib/request.js#L318).

(also—I just switched on the setting in CircleCI to built forked PRs so this should build now if you push again 👍 )

**Comment by Jexordexan** [comment]
You're correct! After doing testing myself, I found the same problem. I've pushed a new commit :)

**Comment by samtgarson** [comment]
Looks good! if you have time to update the test (and maybe test for the default), I'm good to merge 😊

**Comment by Jexordexan** [comment]
Tests are updated and I've verified this works as expected. The circle ci still seems not to hook into the PR, but the tests pass locally.

**Comment by samtgarson** [comment]
@Jexordexan Merged and published 😁  Cheers!

**Pull request merged**
